apiVersion: apps/v1
kind: Deployment
metadata:
  name: valor-reparaciones-service-deployment
  labels:
    app: valor-reparaciones-service-deployment
spec:
  selector:
    matchLabels:
      app: valor-reparaciones-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: valor-reparaciones-service-deployment
    spec:
      containers:
        - name: valor-reparaciones-service
          image: niko085/valor-reparaciones-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PRECIOS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PRECIOS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PRECIOS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PRECIOS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PRECIOS
